### ISSUE TITLE
Docker volume mapping single file instead of directory

### ISSUE THREAD

**Issue by alexpovel** [vincent/sharedlists#1]
Why did you decide for this volume option?

https://github.com/vincent/kisslists/blame/884d249f1b9f37b5dbb4f795145b1c667e85c321/README.md#L25

Seems quite hard to work with and not extensible. What if you wanted to add, say, a `yaml` config file or similar? Then you'd have to repeat the process for each file. This is the first time I see such a mapping!

Usually, it goes:

```yaml
data:/kisslist
```

where `/kisslist` is a directory you as a maintainer/creator can use for *whatever you want*. You can introduce breaking changes, like a change of databases or a new `yaml` config file, and the users will possibly never be affected or have to know about it.

In the above docker-compose mapping, `data` is a named Docker volume. I prefer those to bind mounts, but you could also do that of course:

```yaml
./data:/kisslist
```

The important part is that there's *some* directory and not a direct, single file. In the current version, we can't very well map to the `/` directory ;) Other than that, the user wouldn't have to create empty files initially, also a bonus.

**Comment by vincent** [comment]
Thank you

**Comment by alexpovel** [comment]
Thanks!

However, I would advise to also remove the `VOLUME` instruction, it has almost no use and can do a lot of annoying harm, see AdguardTeam/AdGuardHome/pull/2589.
