### ISSUE TITLE
Replace publish script with Docker Hub automation

### ISSUE THREAD

**Issue by alexpovel** [vincent/sharedlists#2]
The current [publish script](https://github.com/vincent/kisslists/blob/b80a855c8ee35731b477c7042dba289a956a3211/publish.sh) could just be replaced with [automated hub.docker.com builds](https://docs.docker.com/docker-hub/builds/). Since this project is still simple, it should "just work": connect to Docker Hub, point to this repo (Dockerfile is in root already, no paths need to be specified), enable auto-build, done!

**Comment by vincent** [comment]
Thank you
