### ISSUE TITLE
A Pi/ARM compatible version in docker hub

### ISSUE THREAD

**Issue by C-Fu** [vincent/sharedlists#3]
As the title says, a Pi version would be nice. And while I'm just guessing, if it's simple then it should be an easy work? I have no idea how hard it can be TBH.

Keep up the good work!

Also, if I do a docker pull allyouneedisgnu/kisslists it seems to work, but if I search in docker hub all I can find is https://hub.docker.com/r/allyouneedisgnu/sharedlists ?

**Comment by vincent** [comment]
Hi,

I have a Pi at home and will try to release an image.
note to self: see https://github.com/miniflux/v2/blob/master/Makefile 

/sharedlists is an old version, and will be deleted soon.

**Comment by vincent** [comment]
[allyouneedisgnu/kisslists](https://hub.docker.com/r/allyouneedisgnu/kisslists) should now have tags for linux amd64, arm/v6, arm/v7 and arm64
