### ISSUE TITLE
Docker-Compose Error

### ISSUE THREAD

**Issue by ChrissWalters** [vincent/sharedlists#8]
Hi,

by using your Docker-Compose install "script":

kisslists:
  image: allyouneedisgnu/kisslists
  volumes:
    - ./your/kisslists:/kisslists
  ports:
    - 80:80

it throws an error:

"(root) Additional property kisslists is not allowed"

**Comment by Enlargee** [comment]
This caught me out for a moment, too:

It should have a services top level entry: ie. 

```
services:    # <--- this line
  kisslists:
    image: "allyouneedisgnu/kisslists"
    container_name: "kisslist"  # this is optional
    volumes:
      - ${YOURPATH}/kisslists:/kisslists
    ports:
      - 80:80
    networks:      # this is optional, depending on your setup
      - network1  # this is optional
    restart: "unless-stopped"
```

**Comment by vincent** [comment]
Indeed. I made the Readme more clear.
